#!/usr/bin/env python2
# -*- coding: utf-8 -*-

""" Get opw values from currently loaded robot_description """

from __future__ import absolute_import, print_function

import pprint

from urdf_parser_py.urdf import URDF
from urdf_to_opw_kinematics.main import convert

robot = URDF.from_parameter_server()
pp = pprint.PrettyPrinter(indent=4)

print(pp.pprint(convert(robot)))
