#!/usr/bin/env python2
# -*- coding: utf-8 -*-

""" Test motion """

from __future__ import absolute_import, division

import math
import re

import rospkg

import rospy
from geometry_msgs.msg import Point
from pilz_robot_programming.commands import *
from pilz_robot_programming.robot import *

__REQUIRED_API_VERSION__ = "1"  # API version
__ROBOT_VELOCITY__ = 0.5  # velocity of the robot

robot_config = {
    "planning_group": "manipulator",
    "target_link": "rake",
    "reference_frame": "world",
    "default_or": from_euler(0, math.radians(180), 0),
}


def string_to_point(gcode):
    # Convert strings from Gcode file to ROS points
    float_pos = map(float, re.findall("[-+]?\d*\.?\d+|[-+]?\d+", gcode))
    if len(float_pos) == 3:
        # convert from mm to m and round to 4
        point = Point(
            round(float_pos[0], 4), round(float_pos[1], 4), round(float_pos[2], 4),
        )
        return point
    else:
        rospy.logwarn("Non-position value on line")
        return None


def start_program(planning_group, target_link, reference_frame, default_or):

    rospy.loginfo("Program started")  # log

    # Home the robot
    r.move(Ptp(goal=[0, 0, 0, 0, 0, 0], planning_group=planning_group))

    source_file = "studio_points.txt"
    source_path = "{}/share/{}".format(rospack.get_path("studio_motion"), source_file)

    garden_height = 0.4
    radius = 0.01

    # Variables to be populated below
    init_ptp = None
    csv_seq = Sequence()

    # TODO: we should clean the list in advance to make
    # sure the last line is not just a blank line etc.

    with open(source_path, "r") as points_file:
        lines = points_file.readlines()

        # Ptp to first position
        init_point = string_to_point(lines[0])
        init_pose = Pose(
            position=Point(init_point.x, init_point.y, garden_height),
            orientation=default_or,
        )

        init_ptp = Ptp(
            goal=init_pose,
            acc_scale=0.3,
            # vel_scale=__ROBOT_VELOCITY__,
            planning_group=planning_group,
            target_link=target_link,
            reference_frame=reference_frame,
        )

        # Populate Sequence
        for row in lines[1:-1]:
            point = string_to_point(row)
            if point:
                pose = Pose(
                    position=Point(point.x, point.y, garden_height),
                    orientation=default_or,
                )
                rospy.logdebug("Adding point:\n%s", point)

                lin = Ptp(
                    goal=pose,
                    acc_scale=0.1,
                    vel_scale=__ROBOT_VELOCITY__,
                    planning_group=planning_group,
                    target_link=target_link,
                    reference_frame=reference_frame,
                )

                csv_seq.append(lin, blend_radius=radius)

        # Final point in sequence with no radius blend
        final_point = string_to_point(lines[-1])
        final_pose = Pose(
            position=Point(init_point.x, init_point.y, garden_height),
            orientation=default_or,
        )

        final_ptp = Lin(
            goal=final_pose,
            acc_scale=0.1,
            vel_scale=__ROBOT_VELOCITY__,
            planning_group=planning_group,
            target_link=target_link,
            reference_frame=reference_frame,
        )
        csv_seq.append(final_ptp)

    # Run Sequence
    rospy.loginfo("Attempting move.")

    # Ptp to first location
    r.move(init_ptp)

    # Run the Lin Sequence
    try:
        r.move(csv_seq)
        rospy.loginfo("Sequence move finished.")
    except RobotMoveFailed:
        rospy.loginfo("Sequence move failed.")


if __name__ == "__main__":
    # Init a ros node
    rospy.init_node("robot_program_node")
    rospack = rospkg.RosPack()

    # initialisation
    r = Robot(__REQUIRED_API_VERSION__)  # instance of the robot

    # start the main program
    start_program(**robot_config)
