# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1_s:
    min_position: -1.57079632679490
    max_position: 1.57079632679490
    has_velocity_limits: true
    max_velocity: 7.9412
    has_acceleration_limits: true
    max_acceleration: 1
  joint_2_l:
    min_position: -0.62832332421617
    max_position: 2.53073753463160
    has_velocity_limits: true
    max_velocity: 6.7495
    has_acceleration_limits: true
    max_acceleration: 1
  joint_3_u:
    min_position: -1.22173899880980
    max_position: 1.57079632717839
    has_velocity_limits: true
    max_velocity: 9.075699999999999
    has_acceleration_limits: true
    max_acceleration: 1
  joint_4_r:
    min_position: -3.31613921546937
    max_position: 3.31613921546937
    has_velocity_limits: true
    max_velocity: 9.599299999999999
    has_acceleration_limits: true
    max_acceleration: 1
  joint_5_b:
    min_position: -2.35619448947329
    max_position: 2.35619448947329
    has_velocity_limits: true
    max_velocity: 9.599299999999999
    has_acceleration_limits: true
    max_acceleration: 1
  joint_6_t:
    min_position: -6.28319067160695
    max_position: 6.28319067160695
    has_velocity_limits: true
    max_velocity: 17.4845
    has_acceleration_limits: true
    max_acceleration: 1
