# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint_1_s:
    min_position: deg(-90.0) # -170 (hard limits)
    max_position: deg(90.0) # 170
    has_velocity_limits: true
    max_velocity: 7.9412
    has_acceleration_limits: true
    max_acceleration: 60
  joint_2_l:
    min_position: deg(-36) # -65
    max_position: deg(145)
    has_velocity_limits: true
    max_velocity: 6.7495
    has_acceleration_limits: true
    max_acceleration: 20
  joint_3_u:
    min_position: deg(-70)
    max_position: deg(90) # 190
    has_velocity_limits: true
    max_velocity: 9.0757
    has_acceleration_limits: true
    max_acceleration: 15
  joint_4_r:
    min_position: deg(-190)
    max_position: deg(190)
    has_velocity_limits: true
    max_velocity: 9.5993
    has_acceleration_limits: true
    max_acceleration: 30
  joint_5_b:
    min_position: deg(-135)
    max_position: deg(135)
    has_velocity_limits: true
    max_velocity: 9.5993
    has_acceleration_limits: true
    max_acceleration: 20
  joint_6_t:
    min_position: deg(-360)
    max_position: deg(360)
    has_velocity_limits: true
    max_velocity: 17.4845
    has_acceleration_limits: true 
    max_acceleration: 30
