port: /dev/ttyUSB0
baud: 1000000
rate: 100
sync_write: True
sync_read: False
read_rate: 10
write_rate: 10

joints:
  {
    right_arm_shoulder_roll_joint: { id: 3, neutral: 512, invert: True },
    right_arm_elbow_flex_joint: { id: 4, neutral: 512 },
    right_arm_forearm_flex_joint: { id: 5, neutral: 512 },
    right_arm_wrist_flex_joint: { id: 6, neutral: 512 },
    right_arm_shoulder_pan_joint: { id: 19, ticks: 4096, neutral: 2048 },
    right_arm_shoulder_lift_joint:
      { id: 20, ticks: 4096, neutral: 2048, invert: True },
  }

controllers:
  {
    small_arm_controller:
      {
        action_name: small_arm_controller/follow_joint_trajectory,
        type: follow_controller,
        joints:
          [
            right_arm_shoulder_pan_joint,
            right_arm_shoulder_lift_joint,
            right_arm_shoulder_roll_joint,
            right_arm_elbow_flex_joint,
            right_arm_forearm_flex_joint,
            right_arm_wrist_flex_joint,
          ],
      },
  }
