controller_list:
  - name: fake_manipulator_controller
    joints:
      - right_arm_shoulder_pan_joint
      - right_arm_shoulder_lift_joint
      - right_arm_shoulder_roll_joint
      - right_arm_elbow_flex_joint
      - right_arm_forearm_flex_joint
      - right_arm_wrist_flex_joint